"""schema checkpoint

Revision ID: 24d1406e84ab
Revises: b942c9892d32
Create Date: 2026-07-12 23:00:07.300293
"""

from collections.abc import Sequence

revision: str = "24d1406e84ab"
down_revision: str | Sequence[str] | None = "b942c9892d32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
