"""schema checkpoint

Revision ID: b942c9892d32
Revises: e088dc6c8069
Create Date: 2026-07-12 22:52:29.646683
"""

from collections.abc import Sequence

revision: str = "b942c9892d32"
down_revision: str | Sequence[str] | None = "e088dc6c8069"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
