"""remove obsolete path classification columns

Revision ID: e088dc6c8069
Revises: f3dd403b1a99
Create Date: 2026-07-12 22:51:27.195505
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e088dc6c8069"
down_revision: str | Sequence[str] | None = "f3dd403b1a99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paths", "is_nickname")
    op.drop_column("paths", "is_system_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("paths", sa.Column("is_system_path", sa.BOOLEAN(), nullable=False))
    op.add_column("paths", sa.Column("is_nickname", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
