"""create paths table

Revision ID: f3dd403b1a99
Revises:
Create Date: 2026-07-12 21:51:49.569850
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f3dd403b1a99"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paths",
        sa.Column("filepath", sa.String(), nullable=False),
        sa.Column("parent_path", sa.String(), nullable=False),
        sa.Column("normalized_filepath", sa.String(), nullable=False),
        sa.Column("is_nickname", sa.Boolean(), nullable=False),
        sa.Column("is_system_path", sa.Boolean(), nullable=False),
        sa.Column("is_folder", sa.Boolean(), nullable=False),
        sa.Column("is_file", sa.Boolean(), nullable=False),
        sa.Column("is_able_to_watch", sa.Boolean(), nullable=False),
        sa.Column("modified_path_at", sa.DateTime(), nullable=False),
        sa.Column("modified_content_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paths")
    # ### end Alembic commands ###
