from typing import Any, Protocol


class ConfigRepository(Protocol):
    def initialize(self, reset: bool = False) -> None: ...

    def read(self) -> dict[str, Any]: ...

    def replace(self, data: dict[str, Any]) -> None: ...

    def commit(self) -> None: ...
